# Generated by Django 4.1.13 on 2023-11-11 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emptycuptask', '0004_designinstitution_no_of_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designinstitution',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
